[project]
name = "py-uds-address"
description = "Collection of UDS addresses for various ECUs."
requires-python = ">=3.10"
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Telecommunications Industry",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Software Development :: Embedded Systems",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Networking",
]
keywords = [
    "uds",
    "unified-diagnostic-services",
    "automotive",
    "on-board-diagnostic",
    "obd",
    "obd2",
    "vehicle-diagnostic",
    "iso14229",
    "iso-14229",
    "iso15765",
    "iso-15765",
    "ECU",
    "address",
]
authors = [
    {name="Maciej Dąbrowski", email="maciej.dabrowski@software-quality.pl"},
    {name="UDS Package Development", email="uds-package-development@googlegroups.com"},
]
maintainers = [
    {name="Maciej Dąbrowski", email="maciej.dabrowski@software-quality.pl"},
    {name="UDS Package Development", email="uds-package-development@googlegroups.com"},
]
dependencies = [
    "py-uds >= 3"
]
dynamic = ["version"]


[project.urls]
"Homepage" = "https://github.com/mdabrowski1990/uds"
"User Documentation" = "https://uds.readthedocs.io"
"Repository" = "https://github.com/mdabrowski1990/uds-address"
"Issues Tracking System" = "https://github.com/mdabrowski1990/uds-address/issues"
"Releases and Changelogs" = "https://github.com/mdabrowski1990/uds-address/releases"
"PyPI" = "https://pypi.org/project/py-uds-address/"
"Code Download" = "https://github.com/mdabrowski1990/uds-address/archive/refs/heads/main.zip"


[project.optional-dependencies]
static-code-analysis = [
    "prospector == 1.19.1",
    "mypy == 2.3.1",
    "vulture == 2.16",
    "bandit == 1.9.4",
    "pyroma == 5.0.1",
]
dependency-scan = [
    "pip-audit == 2.10.1",
]
sorting-imports = [
    "isort == 9.0.1"
]


[build-system]
requires = [
    "setuptools >= 77.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"


[tool.setuptools]
license-files = ["LICENSE"]


[tool.setuptools.dynamic]
version = {attr = "uds_address.__version__"}


[tool.setuptools.packages.find]
include = ["uds_address*"]


[tool.setuptools.package-data]
"*" = ["README.rst", "CONTRIBUTORS.txt", "LICENSE.txt"]


[tool.isort]
src_paths = ["uds_address"]
line_length = 120
use_parentheses = true
include_trailing_comma = true
force_grid_wrap = 0
multi_line_output = 3
